### ISSUE TITLE
Scanner is broken with Latest Plex pass updates 

### ISSUE THREAD

**Issue by ZeroQI** [binhex/arch-plexpass#11] opened 2019-02-26 00:00 UTC
After updating to Plexpass versions 15.x the scanner would not function giving errors:

Feb 10, 2019 02:36:25.584 [0x14e598e7c740] DEBUG - Directory had 13 files, database had 0 files, can't skip.
Feb 10, 2019 02:36:25.597 [0x14e598e7c740] ERROR - No module in Absolute Series Scanner
Feb 10, 2019 02:36:25.597 [0x14e598e7c740] ERROR - Error in Python: Looking up module: Traceback (most recent call last): File "/config/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 20, in from lxml import etree # fromstring ImportError: libexslt.so.0: cannot open shared object file: No such file or directory

I am running in the binhex/plexpass docker (https://hub.docker.com/r/binhex/arch-plexpass)

Last tested broken build is plex1.15.1.707-1-01. Reverting to 1.14.1.5488-1-01 fixes the scanner issue.
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/204

**Comment by binhex** [comment] 2019-02-26 17:53
not sure what i can tell you, ive made no code changes, the only change as far as im concerned was a bump up in the base image that was done a couple or so weeks ago and the latest version of plex at the time of the build, maybe a bug in the latest version of plex i would assume.

**Comment by ZeroQI** [comment] 2019-02-26 21:57
Make sense.
Thanks for taking the time to respond

**Comment by Hiren-Z** [comment] 2019-03-20 15:31
Issue is only observed in Binhex Plex repositories.  Scanner runs correctly inside the Limetech repo and on a fresh plex install in windows.

**Comment by binhex** [comment] 2019-03-20 16:22
it wont be present in limetch repo as they havent updated to the latest plex pass release 1.15.x and thus didnt see the issue, windows is a completely different platform so i cant comment on that.

the issue is i believe (i dont run plex pass) fixed in 1.15.1.xx which is now the stable version, please update and try it again.

**Comment by Hiren-Z** [comment] 2019-03-20 16:42
I am running current on all 3 

Test 1 (binhex/arch-plexpass) Version 1.15.2.793
Test 2 (binhex/arch-plex)        Version 1.15.1.791
Test 3 (limetech/plex)             Version 1.15.1.791

Limetech actually just updated to 1.15.1* about 2 hours ago.

**Edit**
I also removed, did plex dance, and re-added the libraries ensuring the scanner was selected durring configuration.

**Comment by binhex** [comment] 2019-03-20 17:03
ok firstly keep in mind that although the LT docker image is now up to date it is NOT plex pass version, and thus will most likely be out of step with the plex pass version (fyi pms plex pass=beta) so there could still be some differences between this image and the LT one (and also my non plex pass version). 

having said that if you can detail the exact steps i need to replicate the issue then i will give it a whirl and see if it blows up for me too (will rule out host and/or config issues).

**Comment by Hiren-Z** [comment] 2019-03-20 17:10
Installed a fresh version of each docker (in unraid) so there is no existing config changes that could be effecting the scanner.

Installed the scanner from https://github.com/ZeroQI/Absolute-Series-Scanner

Scanned my anime folder, and nothing populates. 
Log reads as below as mentioned above. (this was taken from your non-plexpass release)
Error in Python: Looking up module:
Traceback (most recent call last):
File "/config/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 20, in <module>
from lxml import etree # fromstring
ImportError: libexslt.so.0: cannot open shared object file: No such file or directory

**Comment by binhex** [comment] 2019-03-20 17:12
hmm a third party scanner eh, that would be your problem then, you did see the issue on that github repo right? :-)

edit - ahh its you hehe, ok well i would expect that scanner is going to be the culprit, there was a LOT of changes in plex 1.15.x and i wouldnt be suprised if the scanner is now broken

**Comment by Hiren-Z** [comment] 2019-03-20 17:18
Any clue how the others have gotten around it not working? I really don't want to go back to the horrible Limetech folder infrastructure, its a CLI nightmare.

**Comment by binhex** [comment] 2019-03-20 17:25
hmm ok a bit more digging, it looks like that references a library in the libxslt package, so perhaps installing that package will fix it, can you try the following:-

1. get to the console of the plex pass container (can do this left click plex icon)
2. issue the following command:-`pacman -S libxslt --noconfirm`
3. restart container for good luck
4. give it a whirl

**Comment by Hiren-Z** [comment] 2019-03-20 17:32
That fix's it in both of your repos! ^_^

Will this fix survive an update to the docker?

**Comment by binhex** [comment] 2019-03-20 17:45
no it wont, but i can now include it in the build, watch out for a new build shortly.

@ZeroQI please could you add in a line into your readme to make it clear that your script relies on the fact that libxslt (XML stylesheet transformation library) is installed, might help somebody else out in the future.

**Comment by ZeroQI** [comment] 2019-03-20 19:10
@binhex Done, thanks for looking into it, you fixed it accurately in one go
@Hiren-Z thanks for all tests, you made this possible to be solved
Readme updated under commit: 
Added as known issue: https://github.com/ZeroQI/Absolute-Series-Scanner/commit/348ee241a1fe8bc8cb923323ad9010a529b8b731
Added as requirement: https://github.com/ZeroQI/Absolute-Series-Scanner/commit/cfb8f8254619293f234bcc6795aa64e600fc53a0

**Comment by Hiren-Z** [comment] 2019-03-20 19:13
Can verify it works under the new builds.  Thank you both for your help on getting this fixed resolved!

**Comment by ZeroQI** [comment] 2019-03-20 19:16
I really only opened a bug report there following your bug report. You did all the work. Beautiful oneliner @binhex. Thanks you both for the assistance.

**Comment by binhex** [comment] 2019-03-20 20:06
A pleasure guys, closing this off.

**Closed as completed by binhex** 2019-03-20 20:06 UTC
